#!/bin/csh
# This is a script to copy files from antelope contrib libseispp library
# to this work area.  This probably will be called from a Makefile 
# which would copy the files from regular antelope contrib to here
# and then compile the code.
# 
# The Makefile will also require a make clean that will remove everything
# but the makefile and this script.
set seispphome=/opt/antelope/5.3/src/contrib/lib/seismic/libseispp
echo Attempting to copy required libseispp modules from $seispphome
foreach f (`cat files_to_copy_from_libseispp`)
    cp ${seispphome}/$f .
    echo Copied source code file $f
end
