LIB=libstock.a
OBJS=arr.o \
  elog.o \
  hook.o \
  ssearch.o \
  rb_delete.o \
  rb_free.o \
  rb_init.o \
  rb_insert.o \
  rb_level_traverse.o \
  rb_lshow.o \
  rb_search.o \
  rb_show.o \
  rb_traverse.o \
  rb_vcg.o \
  strings.o \
  tbl.o \
  wd.o
$(LIB) : $(OBJS)
	ar rv $@ $(OBJS)
