.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:18:59 $


.TH banner 3 "$Date: 1997/04/12 04:18:59 $" 
.SH NAME
banner \- print a standard banner
.SH SYNOPSIS
.nf

void banner(char *program, char *version)

.fi
.SH DESCRIPTION
This routine is used to print a header announcing the name of the
\fIprogram\fP, the \fIversion\fP, and the \fIJSPC\fP address.  It is used
by interactive programs to standardize the greeting message.
.SH "SEE ALSO"
style(5)

.\" $Id: banner.3,v 1.1.1.1 1997/04/12 04:18:59 danq Exp $ 
