'\" te


.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:18:59 $
.EQ
delim $$
.EN
.TH COMPRESS 3 "$Date: 1997/04/12 04:18:59 $"
.SH NAME
compress \- compress files in background
.SH SYNOPSIS
.nf
void compress (path)
.fi
.SH DESCRIPTION
This is just a programmatic interface to the compress 
program -- it runs compress in the background on the passed
path, and returns immediately.  Failures of compress are not
reported.
.SH FILES
compress runs the program /usr/ucb/compress.
.SH EXAMPLE
    compress ( "wf/19923230935.w" ) ; 
.SH LIBRARY
libstock.a
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
Compress may fail for a variety of reasons, but failures are not
reported.
.SH AUTHOR
Daniel Quinlan

.\" $Id: compress.3,v 1.1.1.1 1997/04/12 04:18:59 danq Exp $ 
