.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:18:59 $


.TH DUMP 3 "$Date: 1997/04/12 04:18:59 $"
.SH NAME
dump \- print formatted hexadecimal/alphanumeric of memory
.SH SYNOPSIS
.nf
void dump ( char *a, int l );
.fi
.SH DESCRIPTION
This just prints an error of memory to stderr, in the
standard IBM 360 type hexadecimal/ascii format.
.SH LIBRARY
-lstock
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
Daniel Quinlan

.\" $Id: dump.3,v 1.1.1.1 1997/04/12 04:18:59 danq Exp $ 
