.\" $Name:  $ $Date: 1998/02/17 22:39:37 $
.TH EXPAND_ENV 3 "$Date: 1998/02/17 22:39:37 $"
.SH NAME
expand_env \- substitute environment variables into string
.SH SYNOPSIS
.nf
char * expand_env ( char *s );
.fi
.SH DESCRIPTION
expand_env searches the string \fIs\fR for occurrences of '$' and 
replaces the following alphanumeric string with the corresponding
environment value, much as the shells substitute environment variables.
Strings may be delimited with curly braces to allow the expansion to 
be followed by an alphabetic string.
.SH ENVIRONMENT
.SH EXAMPLE
.RS .2i
.RE
.SH RETURN VALUES
The return value is a string which has been malloc'd, and must
be freed by the caller.
.SH LIBRARY
-lstock
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
Daniel Quinlan
