.TH QUICKSORT 3 "$Date: 1997/04/12 04:19:01 $"
.SH NAME
quicksort \- quick sort implementation
.SH SYNOPSIS
.nf
void quicksort ( char *a, int n, int size, int (*compare)(), void *private );
.fi
.SH DESCRIPTION
This is an implementation of quick sort, taken from the bsd source
see the licensing terms below, with modifications to pass along
an extra argument, private, to the comparison routine.
.LP
A is the array to be sorted, n is the number of elements in the array,
size is the size (in bytes) of an element of the array, compare is a comparison
routine which is called as follows:
.nf
(*compare) ( element1, element2, private )
.fi
where element1 and element2 are pointers to elements of the array, and
private is whatever you like (which may be nothing).
On the other hand, \fIa\fR might be an array of indexes into a second
array which is given by private.
Compare should return an integer which is (<0, ==0, >0) when
(*element1 < *element2, *element1 == *element2, *element1 > *element2 ).

.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.SH RETURN VALUES
none
.SH LIBRARY
-lstock
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf
shellsort(3)
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
 Copyright (c) 1990, 1991 The Regents of the University of California.

 This code is derived from software contributed to Berkeley by
 the American National Standards Committee X3, on Information
 Processing Systems.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. All advertising materials mentioning features or use of this software
    must display the following acknowledgement:
	This product includes software developed by the University of
	California, Berkeley and its contributors.
 4. Neither the name of the University nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

.\" $Id: quicksort.3,v 1.1.1.1 1997/04/12 04:19:01 danq Exp $ 
