'\" te


.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:19:02 $
.EQ
delim $$
.EN
.TH SHELLSORT 3 "$Date: 1997/04/12 04:19:02 $"
.SH NAME
shellsort \- shell sort implementation
.SH SYNOPSIS
.nf
void shellsort ( char *a, int n, int size, int (*compare)(), void *private );
.fi
.SH DESCRIPTION
This is an implementation of a shell sort, taken from 
\fIAlgorithms in Modula-3\fR by Robert Sedgewick, pp 109.  
This is a relatively good sort, 
though qsort(3) may in general be a 
better choice.  However, this shellsort allows passing additional information
to the compare routine via the private pointer.
.LP
A is the array to be sorted, n is the number of elements in the array, 
size is the size (in bytes) of an element of the array, compare is a comparison
routine which is called as follows:
.nf
(*compare) ( element1, element2, private ) 
.fi
where element1 and element2 are pointers to elements of the array, and
private is whatever you like (which may be nothing).
On the other hand, \fIa\fR might be an array of indexes into a second 
array which is given by private.
Compare should return an integer which is (<0, ==0, >0) when
(*element1 < *element2, *element1 == *element2, *element1 > *element2 ). 
.LP
\fBShellsort\fR sorts the array in memory by moving the elements of the
array.
.SH EXAMPLE
.nf
int compare ( a, b, private ) 
int *a, *b ; 
{ 
    return *a-*b ; 
}
 
int show_table ( table, n ) 
int *table; 
int n ;
{
    int i ; 
    for ( i=0 ; i<n ; i++ ) 
        printf ( " %d ", table[i] ) ; 
    printf ( "\en" ) ; 
}
 
static int table[] = { 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 } ; 
static int n = sizeof(table)/sizeof(int) ; 
 
main (argc, argv ) 
int argc ;
char *argv ; 
{
    show_table ( table, n ) ; 
    shellsort ( table, n, sizeof(int), compare, 0 ) ; 
    show_table ( table, n ) ; 
}
.fi
.SH RETURN VALUES
none
.SH LIBRARY
libstock.a
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf
qsort(3)
.fi
.SH "BUGS AND CAVEATS"
Qsort may often be a better choice; the major advantage of shellsort is
the private pointer.
.SH AUTHOR
Daniel Quinlan

.\" $Id: shellsort.3,v 1.1.1.1 1997/04/12 04:19:02 danq Exp $ 
