.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:19:02 $


.TH STR 3 "$Date: 1997/04/12 04:19:02 $"
.SH NAME
blank, whitespace, split \- string utility functions
.SH SYNOPSIS
.nf
int blank ( char *s );
int whitespace ( char *s );

Tbl *split ( char *string, char c );

void sncopy ( char *dest, char *source, int n );
void szcopy ( char *dest, char *source, int n );
void copystrip ( char *dest, char *source, int n );

.fi
.SH DESCRIPTION
\fBblank\fR returns non-zero if the null-terminated string s 
is composed entirely of blank characters.
.LP
\fBwhitespace\fR returns non-zero if the null-terminated string s 
is composed entirely of whitespace characters: space, tab, or newline.
.LP
\fBsplit\fR splits a string into component pieces in the same way
that awk does, returning a Tbl with all the components.  Repeated
character 'c' are the same as a single 'c', and leading 'c's are 
ignored.  The input string is overwritten in the process.
.LP
\fBsncopy\fR copies a string with \fIn\fR maximum characters
from \fIsource\fR to \fIdest\fR, padding with spaces if necessary.
No null character is appended.
.LP
\fBszcopy\fR copies exactly \fIn\fR characters
from \fIsource\fR to \fIdest\fR, and then appends a 
null character.
.LP
\fBcopystrip\fR copies a string of \fIn\fR characters
from \fIsource\fR to \fIdest\fR, stripping leading and trailing
blanks and appending a 
null character.  
.SH EXAMPLE
.SH RETURN VALUES
.SH LIBRARY
-lstock
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf

.fi
.SH "BUGS AND CAVEATS"

.SH AUTHOR
Daniel Quinlan

.\" $Id: strings.3,v 1.1.1.1 1997/04/12 04:19:02 danq Exp $ 
