.TH TEMPLATE 1 "$Date: 1997/04/12 04:19:03 $" "DSAP Release 1.0"
.SH NAME
template.c \- generic C template with nice features
.SH DESCRIPTION
The file \fBtemplate.c\fP is a C language program template designed to
ease writing C programs.  It uses the \fBtmpl(3)\fP package to do the
parsing, and the \fBerror_handling(3)\fP package to report errors.  The
interested user should consult those manuals for more detailed
information.
.LP
To use the template the the user should edit the sections marked by
``%%%%'', and replace them with whatever is appropriate.  Then the user
should replace / modify the \fBprocess()\fP routine to perform whatever
it is the program is supposed to do.
.SH EXAMPLE
As \fBtemplate.c\fP consists now, it is roughly equivalent to cat, without
all the fancy display features.  It simply cycles through a set of input
files, and writes the contents to the output file.  
.LP
The best explanation is to work through the source code and see how the
following examples are handled.
.LP
.RS
.nf
shell% ls
.LP
shell% template - foo
first line of foo
^D
.LP
shell% cat foo
first line of foo
.LP
shell% template foo bar
.LP
shell% cat bar
first line of foo
.LP
shell% template foo bar -
first line of foo
first line of foo
.LP
shell% ls
.ta 20n
bar	foo
.LP
shell% template foo bar -- -out
.LP
shell% ls
.ta 20n +20n
bar	foo	-out
.fi
.RE
.SH FILES
.TP 25
template.c
the C source file itself.
.SH "SEE ALSO"
tmpl(3), error_handling(3)
.SH AUTHOR
Eric Winkelman
.br
University of Colorado \- Physics department
.br
ewink@lemond.Colorado.EDU

.\" $Id: template.1,v 1.1.1.1 1997/04/12 04:19:03 danq Exp $ 
