.TH WD 3 "$Date: 1997/04/12 04:19:03 $"
.SH NAME
mappath \- library routines for translating pathnames
.SH SYNOPSIS
.nf
int mappath ( char *spath, char *upath );
.fi
.SH DESCRIPTION
The routines in this library map pathnames from a system dependent
format to a configurable, system independent format.  
.LP
mappath (spath, dpath)
.br
char *spath, *dpath;
.IP
Copy
.I spath
to
.I dpath.
If
.I spath
matches any of the regular expressions found in the config file, then
the corresponding replacement string is copied to
.I dpath.
If no matches are found,
.I spath
is copied unmodified to
.I dpath
.LP
setmapcf (fn)
.br
char *fn;
.IP
Set the name of the configuration file.  If this function is not called
the default file will be used (currently $DSAP/data/wd.cf).
.LP
readmap ()
.br
.IP
Read configuration file.  Each line of this file consists of a regular
expression, white space, and a replacement string.  mappath() calls this
function if it is not called by the application.
.SH FILES
$DSAP/data/wd.cf contains the configuration file.
.SH ENVIRONMENT
This file may be overridden with the environment variable MAPPATH.
.SH LIBRARY
-lstock
.SH "SEE ALSO"
uwd(1), pathf(1)
.SH BUGS AND CAVEATS
\fISpath\fR and \fIupath\fR \fBmust\fR be distinct.
.SH AUTHOR
.nf
Bob Schwartzkopf, The RAND Corporation
modified by Daniel Quinlan

.\" $Id: wd.3,v 1.1.1.1 1997/04/12 04:19:03 danq Exp $ 
