.\" $Name $Revision: 1.1.1.1 $ $Date: 1997/04/12 04:19:03 $


.TH  ZOPEN 3 "$Date: 1997/04/12 04:19:03 $"
.SH NAME
zopen, gz_open, gz_cat \- opens a compressed file
.SH SYNOPSIS
.nf
FILE *zopen ( filename, permissions ) 
char *filename ; 
char *permissions ; 

FILE *gz_open ( filename, permissions ) 
char *filename ; 
char *permissions ; 

FILE *gz_cat ( filename, permissions ) 
char *filename ; 
char *permissions ; 
.fi
.SH DESCRIPTION
\fBZopen\fR has the same arguments as fopen, but if the 
filename ends in .Z or .gz, it will uncompress the compressed file
into a temporary file on /usr/tmp (or in the 
directory named in the environment variable TMPDIR), and
then open that file.  The file is immediately unlinked, so it
will remain only as long as the process is executing.
.LP
\fBgz_open\fR is identical to \fBzopen\fR, but the name change avoids
a conflict with a similar name used in sac.
.LP
\fBgz_cat\fR is similar to \fBzopen\fR, but it runs zcat on the
compressed file and returns a FILE which is open to the output
of zcat.  In this case, the permissions argument must always be
"r".
.SH FILES
Creates a file in /usr/tmp, but file is invisible 
because it is immediately unlinked.
.SH RETURN VALUES
NULL indicates failure, otherwise a FILE pointer.
.SH LIBRARY
-lstock
.SH DIAGNOSTICS
none
.SH "SEE ALSO"
.nf
tempnam(3), zcat(1)
.fi
.SH "BUGS AND CAVEATS"
You can fill up /usr/tmp (or TMPDIR) by using \fBzopen\fR or \fBgz_open\fR indiscriminately;
to delete the file before the completion of execution, close the 
file with fclose.
.LP
Both routines depend on GNU zcat being installed on the path ahead of
the standard UNIX zcat which only understands Lempel-Ziv compression.
.SH AUTHOR
Daniel Quinlan

.\" $Id: zopen.3,v 1.1.1.1 1997/04/12 04:19:03 danq Exp $ 
