LIB=libpwmig.a
INCLUDE=PwmigFileHandle.h
#MAN3=		# man pages for library routines
include $(ANTELOPEMAKE)

OBJS=PwmigFileHandle.o PPWDeconProcessor.o
PPWDeconProcessor.o :PPWDeconProcessor.h

$(LIB) : $(OBJS)
	$(RM) $@
	$(CXXAR) $(CXXARFLAGS) $@ $(OBJS)  
	$(RANLIB) $@
